### ISSUE TITLE
bug: JavaScript heap out of memory on certain requests

### ISSUE THREAD

**Issue by mve** [PassTheMayo/minecraft-server-util#63]
**Describe the bug:**
Certain requests that worked on V4 are now causing JavaScript heap out of memory on V5.
For example this server.
"host": "play.minelatino.com",
"port": 25565,

On v4 i was able to ping upwards of 100 servers at one time without any issues, on v5 this was giving me this error and i was able to narrow it down to have it crash on just one server.
Im sure i could find more servers that are causing issues, this was just the first one i found.

**Code:**
```javascript
// Example code

    return status("play.minelatino.com", 25565).catch((e) => {
      if (e === undefined) {
        return { error: 'Error is undefined.', request: host }
      }
      return { error: e, request: host }
    });

// Output
<--- Last few GCs --->

[26877:0x120008000]    15966 ms: Scavenge 4027.5 (4083.9) -> 4025.6 (4083.9) MB, 2.9 / 0.0 ms  (average mu = 0.168, current mu = 0.101) allocation failure 
[26877:0x120008000]    15973 ms: Scavenge 4030.7 (4087.1) -> 4028.8 (4087.1) MB, 2.9 / 0.0 ms  (average mu = 0.168, current mu = 0.101) allocation failure 
[26877:0x120008000]    16135 ms: Scavenge (reduce) 4034.2 (4090.6) -> 4032.2 (4087.6) MB, 1.2 / 0.0 ms  (average mu = 0.168, current mu = 0.101) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10044e36c node::Abort() [/usr/local/bin/node]
 2: 0x10044e4f4 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x10059b378 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10059b30c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10071eafc v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x100722104 v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 7: 0x10071f2c4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10071cbec v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10071ba54 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
10: 0x1006d0ccc v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
11: 0x100a302d4 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x100d4508c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
13: 0x105037dbc 
14: 0x100cd8d18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
15: 0x100cd8d18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
16: 0x100cd8d18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
17: 0x100d0a4ec Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
18: 0x100cd8d18 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
19: 0x100d8d1b8 Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
20: 0x100cfa6f4 Builtins_RunMicrotasks [/usr/local/bin/node]
21: 0x100cd69e4 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
22: 0x1006ab1e8 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
23: 0x1006ab61c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
24: 0x1006ab6e4 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
25: 0x1006ce48c v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
26: 0x1006ced20 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
27: 0x10060832c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
28: 0x100607e24 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
29: 0x1006076b0 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
30: 0x100d451cc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
31: 0x105021af8 
32: 0x100cd6b0c Builtins_JSEntryTrampoline [/usr/local/bin/node]
33: 0x100cd67a4 Builtins_JSEntry [/usr/local/bin/node]
34: 0x1006ab220 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
35: 0x1006aa8b4 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
36: 0x1005b7e70 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
37: 0x10039de40 node::InternalCallbackScope::Close() [/usr/local/bin/node]
38: 0x10039e36c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
39: 0x1003b34ac node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
40: 0x1004f43dc node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/usr/local/bin/node]
41: 0x1004f6694 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/usr/local/bin/node]
42: 0x1004fad84 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/usr/local/bin/node]
43: 0x100cc4498 uv__stream_io [/usr/local/bin/node]
44: 0x100ccc5b8 uv__io_poll [/usr/local/bin/node]
45: 0x100cbad34 uv_run [/usr/local/bin/node]
46: 0x10039ee00 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
47: 0x1004876f4 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
48: 0x1004873c0 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
49: 0x1004202dc node::Start(int, char**) [/usr/local/bin/node]
50: 0x104e8d0f4 

```

**Expected behavior:**
To get a response with the server status or an error message.

**Additional context**
Using Node.js version 16.13.0
Using minecraft-server-util version 5.2.1

**Comment by 404invalid-user** [comment]
I have been having this error for a while unfortunately. Updating to nodejs v17 will fix it 50% of the time

**Comment by PassTheMayo** [comment]
I have found a potential memory leak with the event emitter system used in the TCP/UDP classes. I just published version `5.2.2` which resolves this issue through extensive testing. Let me know if this solves the problem.

**Comment by mve** [comment]
I'm still getting OOM crashes, now on this host and port for example:
"host": "join.mineheroes.org",
"port": 25565,

The server i used as an example above now seems to work, but i don't run that server so i can't say for sure if they maybe changed some setting.

**Comment by PassTheMayo** [comment]
I was able to reproduce the bug on my end with the second address you provided. I will let you know when I find anything.

**Comment by PassTheMayo** [comment]
I found the problem and narrowed it down to an infinite loop bug within the `minecraft-motd-util` dependency. This has been fixed in `1.1.9`, so use `npm install minecraft-motd-util@1.1.9` and confirm that this has been fixed.

**Comment by mve** [comment]
It seems to be working for me with the new version of minecraft-motd-util.

**Comment by PassTheMayo** [comment]
Good news, I'll go ahead and close this.
