### ISSUE TITLE
bug: statusLegacy `socket.connect` Call Does Not Handle Exceptions

### ISSUE THREAD

**Issue by Jordan9232** [PassTheMayo/minecraft-server-util#65]
**Describe the bug:**
Calling the statusLegacy function will sometimes throw the following error:
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: connect ECONNREFUSED 74.63.195.30:2000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '74.63.195.30',
  port: 2000
}

Node.js v17.1.0
```

Upon investigation, I found in the `statusLegacy` function that a whole block of code is not in a `try` block like it should be. I compared this function with the `status` function and I see that it is properly in a try block there, so this is only an issue with `statusLegacy`. I can't even properly catch it myself because the code is wrapped in its own `return new Promise`

**Code:**
This entire block should be in the `try` block at the end
```
let srvRecord = null;

if (typeof options === 'undefined' || typeof options.enableSRV === 'undefined' || options.enableSRV) {
  srvRecord = await resolveSRV(host);

  if (srvRecord) {
    host = srvRecord.host;
    port = srvRecord.port;
  }
}

socket = new TCPClient();

await socket.connect({ host, port, timeout: options?.timeout ?? 1000 * 5 });

try {
  // Client to server packet
  // https://wiki.vg/Server_List_Ping#Client_to_server
	
  ...
```

**Expected behavior:**
Code should be moved to the try block to properly handle the exception

**Additional context**
```
try {
  const legacy_status = await statusLegacy(host, port);
}
catch (error: any) {
  // can't get here
  console.log(error);
}
```

**Comment by Jordan9232** [comment]
Actually, you might want to check out the `statusBedrock` function as well. All of the following code is also not in a try block:
```
let srvRecord = null;

if (typeof options === 'undefined' || typeof options.enableSRV === 'undefined' || options.enableSRV) {
  srvRecord = await resolveSRV(host, 'udp');

  if (srvRecord) {
    host = srvRecord.host;
    port = srvRecord.port;
  }
}

socket = new UDPClient(host, port);
```

**Comment by PassTheMayo** [comment]
I just fixed this issue on all related methods in version `5.2.5`. Please update by using `npm i minecraft-server-util@5.2.5` and confirm that this has been fixed.

**Comment by Jordan9232** [comment]
Can confirm that this is fixed now. Thanks!

**Comment by Jordan9232** [comment]
@PassTheMayo Actually there's still an issue with the `statusBedrock` function. I've only seen this error happen once and can't seem to get it to happen again so it only seems to happen some of the time:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at new NodeError (node:internal/errors:371:5)
    at healthCheck (node:dgram:917:11)
    at Socket.close (node:dgram:749:3)
    at UDPClient.close (C:\Users\Jordan.TB\Documents\Personal\Minecraft WorldShare\server\node_modules\minecraft-server-util\dist\structure\UDPClient.js:387:68)
    at Object.<anonymous> (C:\Users\Jordan.TB\Documents\Personal\Minecraft WorldShare\server\node_modules\minecraft-server-util\dist\statusBedrock.js:104:68)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jordan.TB\Documents\Personal\Minecraft WorldShare\server\node_modules\minecraft-server-util\dist\statusBedrock.js:6:65) {
  code: 'ERR_SOCKET_DGRAM_NOT_RUNNING'
}

Node.js v17.1.0
```

The only difference I notice is the in statusBedrock the `socket` is set like this:
```
const socket = new UDPClient(host, port);
```

This differs from `status` and `statusLegacy`:
```
const socket = new TCPClient();
```

And then there is this call afterwards which is in a try block:
```
await socket.connect({ host, port, timeout: options?.timeout ?? 1000 * 5 });
```

statusBedrock doesn't have this `socket.connect` call at all. I'm assuming doing `new UDPClient(host, port);` is essentially doing the same thing.

**Comment by mve** [comment]
Just had the same error as @Jordan9232 . Also can't seem to recreate it with a specific server. But it happened for me when pinging a batch of 100 servers, 3 of them were bedrock.
``` 
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at new NodeError (node:internal/errors:371:5)
    at healthCheck (node:dgram:917:11)
    at Socket.close (node:dgram:749:3)
    at UDPClient.close (/Users/mve/code/mc-pinger-serverless/node_modules/minecraft-server-util/dist/structure/UDPClient.js:387:68)
    at /Users/mve/code/mc-pinger-serverless/node_modules/minecraft-server-util/dist/statusBedrock.js:104:68
    at Generator.throw (<anonymous>)
    at rejected (/Users/mve/code/mc-pinger-serverless/node_modules/minecraft-server-util/dist/statusBedrock.js:6:65) {
  code: 'ERR_SOCKET_DGRAM_NOT_RUNNING'
}

Node.js v17.3.0
```

**Comment by PassTheMayo** [comment]
I believe I have resolved the issue with the little information that Node provides about this error. Please update to `5.2.6` and confirm that this has been fixed.

**Comment by mve** [comment]
It seems to be fixed for me, haven't had the issue again on 5.2.6.

**Comment by PassTheMayo** [comment]
Awesome, I’ll go ahead and close this issue the .
